### ISSUE TITLE
Steps for implementation

### ISSUE THREAD

**Issue by ankitcse** [ymfa/seq2seq-summarizer#2]
Hello,
I hope you are doing good.
I was going through your code and found it pretty interesting. There are lot of things which I can learn from this. It would be really helpful if you can also describe some installation steps or starting steps about format of data and how to train this model and what are the software requirements of this model.

Thank you.

**Comment by ymfa** [comment]
Thanks for your comment. I'll certainly add more documentation when I have time.

**Comment by ymfa** [comment]
I have updated README.md with more details on how to train/test the summarizer, the expected data format, and the software dependencies.
