### ISSUE TITLE
Rouge score / training for basic seq2seq attention : too slow training

### ISSUE THREAD

**Issue by Colanim** [ymfa/seq2seq-summarizer#8]
I'm trying to run your (very great) code using a basic seq2seq with attention architecture, in order to get rouge scores.

In order to get a basic seq2seq architecture, I used following parameters :

```
python train.py --vocab_size 50000 --hidden_size 256 --dec_hidden_size 256 --embed_size 128 --pointer False --enc_attn_cover False --cover_loss 0 --optimizer adagrad --lr 0.15 --batch_size 16 --n_batches 2000 --val_batch_size 16 --n_val_batches 200 --grad_norm 2 --min_out_len 40 --max_out_len 120 --embed_file None
```

(removing coverage mecanism, pointer network, RL, and setting same parameters as described in the paper [Get to the Point](https://arxiv.org/pdf/1704.04368.pdf))

I'm training on CNN / DailyMail dataset.

---

My problem is : training is way too long. 

It takes 6sec per iteration (training on GPU), with a batch size of 16 it means 17 500 iterations / epochs => 29h per epoch.

In the paper, they trained the model for 33epochs, which would mean **more than a month of training time with this implementation.**

---

**Why is it so slow to train ? How can I fix it ?**

**Comment by xcfcode** [comment]
Hi, I use the same hyper-params as pointer-generator. It takes about 1h to train an epoch. The problem is that I can not reproduce the result on CNNDM datasets. And, I have changed some codes related to the attention, replace bilinear function with bahdanau attention, It takes about 20min to train an epoch. I hope it helps.

**Comment by Colanim** [comment]
Hi, thanks for your answer. 

Is it possible for you to share your code ? Also can you share the exact command line you used to reach 1h/epoch ? Because no matter what I do the training is still very slow...

**Comment by xcfcode** [comment]
You can refer to this link https://github.com/xcfcode/seq2seq-summarizer, I don't know if it's appropriate behavior to share your code in this way? @ymfa ,I hope it helps. I have changed some codes including attention function(params.attn_func_name), way to choose a model(params.choose_model) and the way to create the secondary experimental dir(params.model_path_prefix), you can just run CUDA_VISIBLE_DEVICES=0 python train.py.

**Comment by Colanim** [comment]
Wow ! Amazing ! It works !!!

Much faster : 1.8 iterations per second => 2.7 hours per epochs, which is much closer to the time mentioned in the paper.

Now I just have to wait and see the results :)

@xcfcode thanks a lot for sharing your fork. Also your default param were more convenient as it match the param used in the paper !

**Comment by xcfcode** [comment]
It's a great pleasure.
